# Generated by Django 4.2.7 on 2023-12-25 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='static/images/')),
                ('profile_summary', models.TextField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=12, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stripeCustomerId', models.CharField(blank=True, max_length=255, null=True)),
                ('stripeSubscriptionId', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
