# Generated by Django 4.2.7 on 2023-12-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0003_remove_profile_stripecustomerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
    ]
