# Generated by Django 4.2.7 on 2023-12-26 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0005_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripeCustomerId',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='stripeSubscriptionId',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
