# Generated by Django 4.2.6 on 2024-01-22 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0011_alter_profile_stripepaiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripePaidDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 20, 34, 5, 994699)),
        ),
    ]
