# Generated by Django 4.2.6 on 2024-02-11 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0012_alter_profile_stripepaiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripePaidDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 19, 37, 41, 466904)),
        ),
    ]
